version: '3'
services:
  task-management:
    image: task-management-system:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: taskmanagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
